name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo 'Hello peeps from the pipeline!'

  test-utils:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and clone repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Test utils
        run: npm run test-utils

  test-app:
    needs: test-utils
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and clone repo
        uses: actions/checkout@v3

      - name: Setup PSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: my_random_test_db
          postgresql user: mr_testerson
          postgresql password: pa55word

      - name: Install dependencies
        run: npm install

      - name: Test app
        run: PGDATABASE=my_random_test_db PGUSER=mr_testerson PGPASSWORD=pa55word npm run test-app
